import { promises as fs } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

import fg from "fast-glob";

import { locales, defaultLocale } from "../config";

const translationLocales = Object.keys(locales)
  .filter((locale) => locale !== defaultLocale)
  .sort();

const REPO_ROOT = process.cwd();
const configPath = path.join(REPO_ROOT, "src/i18n/moneropedia/po4a.conf");
const templateDir = path.join(REPO_ROOT, "src/i18n/moneropedia/template");
const localesDir = path.join(REPO_ROOT, "src/i18n/moneropedia/locales");

const header = `# Auto-generated by gen-config.ts - DO NOT EDIT MANUALLY
[po4a_langs] ${translationLocales.join(" ")}
[po4a_paths] src/i18n/moneropedia/template/$master.pot $lang:src/i18n/moneropedia/locales/$lang/$master.po

[options] \\
  opt:"--master-charset=UTF-8" \\
  opt:"--localized-charset=UTF-8" \\
  opt:"--porefs=file" \\
  opt:"--msgmerge-opt=--no-wrap" \\
  opt:"--wrap-po=newlines"

[po4a_alias:moneropedia] text \\
  opt:"--option markdown" \\
  opt:"--option neverwrap" \\
  opt:"--option yfm_keys=summary,title,terms" \\
  opt:"--keep=90"
`;

async function buildConfig(): Promise<{
  config: string;
  validEntries: Set<string>;
}> {
  const filePattern = `src/content/moneropedia/${defaultLocale}/**/*.md`;
  const files = await fg(filePattern, { cwd: REPO_ROOT, onlyFiles: true });
  if (!files.length) {
    throw new Error(`No Moneropedia entries found via ${filePattern}`);
  }

  const validEntries = new Set<string>();
  const lines = files.sort().map((relativePath) => {
    const normalizedPath = relativePath.split(path.sep).join(path.posix.sep);
    const localized = normalizedPath.replace(`/${defaultLocale}/`, "/$lang/");
    const entryId = path.posix.basename(
      normalizedPath,
      path.posix.extname(normalizedPath),
    );
    validEntries.add(entryId);
    return `[type: moneropedia] ${normalizedPath} $lang:${localized} pot=${entryId}`;
  });

  return { config: `${header}\n${lines.join("\n")}\n`, validEntries };
}

async function main() {
  if (!translationLocales.length) {
    throw new Error("No translation locales configured");
  }

  const { config, validEntries } = await buildConfig();

  const potFiles = await fg("*.pot", { cwd: templateDir, onlyFiles: true });
  const orphans = potFiles.filter(
    (f) => !validEntries.has(path.basename(f, ".pot")),
  );
  await Promise.all(
    orphans.flatMap((potFile) => {
      const entryId = path.basename(potFile, ".pot");
      console.log(`Removed orphan: ${entryId}`);
      return [
        fs.unlink(path.join(templateDir, potFile)),
        ...translationLocales.map((locale) =>
          fs
            .unlink(path.join(localesDir, locale, `${entryId}.po`))
            .catch(() => {}),
        ),
      ];
    }),
  );

  await fs.writeFile(configPath, config, "utf8");
  console.log(`Generated ${configPath}`);
}

const entryPoint = process.argv[1];
if (entryPoint && import.meta.url === pathToFileURL(entryPoint).href) {
  main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
