import { promises as fs } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

import fg from "fast-glob";

import { locales, defaultLocale } from "../config";

const translationLocales = Object.keys(locales)
  .filter((locale) => locale !== defaultLocale)
  .sort();

const REPO_ROOT = process.cwd();
const configPath = path.join(REPO_ROOT, "src/i18n/moneropedia/po4a.conf");

const header = `# Auto-generated by gen-config.ts - do not edit manually
[po4a_langs] ${translationLocales.join(" ")}
[po4a_paths] src/i18n/moneropedia/template/$master.pot $lang:src/i18n/moneropedia/locales/$lang/$master.po

[options] \\
  opt:"--master-charset=UTF-8" \\
  opt:"--localized-charset=UTF-8" \\
  opt:"--porefs=file" \\
  opt:"--msgmerge-opt=--no-wrap" \\
  opt:"--wrap-po=newlines"

[po4a_alias:moneropedia] text \\
  opt:"--option markdown" \\
  opt:"--option neverwrap" \\
  opt:"--option yfm_keys=summary,title,terms" \\
  opt:"--keep=90"
`;

async function buildConfig(): Promise<string> {
  const filePattern = "src/content/moneropedia/en/**/*.md";
  const files = await fg(filePattern, { cwd: REPO_ROOT, onlyFiles: true });
  if (!files.length) {
    throw new Error(`No Moneropedia entries found via ${filePattern}`);
  }

  const lines = files.sort().map((relativePath) => {
    const normalizedPath = relativePath.split(path.sep).join(path.posix.sep);
    const localized = normalizedPath.replace(`/${defaultLocale}/`, "/$lang/");
    const entryId = path.posix.basename(
      normalizedPath,
      path.posix.extname(normalizedPath),
    );
    return `[type: moneropedia] ${normalizedPath} $lang:${localized} pot=${entryId}`;
  });

  return `${header}\n${lines.join("\n")}\n`;
}

async function main() {
  if (!translationLocales.length) {
    throw new Error("No translation locales configured");
  }

  const config = await buildConfig();
  await fs.writeFile(configPath, config, "utf8");
  console.log(`Generated ${configPath}`);
}

const entryPoint = process.argv[1];
if (entryPoint && import.meta.url === pathToFileURL(entryPoint).href) {
  main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
