name: Check Links

on:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.1
        with:
            args: --config ./.github/config/lychee.toml
            format: markdown
            output: ./lychee/out.md
            fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}